#!/usr/bin/env bash
#
# Build Docker images for various Linux distros. These will be used to manually test the
# NadekoBot Manager scripts in different environments.
#
# NOTES:
#   - To run the images, use the following command:
#       - docker run --privileged --rm -it -v "$(pwd)/shared:/root" <image_name_tag>
#   - Upon running/accessing the container, you'll be prompted for a username and
#     password. Use the following credentials:
#       - Username: root
#       - Password: password
#   - To exit the container, execute `shutdown now`, instead of `exit`.
#   - WARNING: The images generated by this script are to be used for testing purposes
#     only. They are not designed for production use, due to:
#       - The hardcoded password.
#       - The use of the `--privileged` flag.
#       - Etc.
#
########################################################################################

set -e

# This associative array maps a distro key to the base image.
# (Use official images when available. For Linux Mint, we rely on community images.)
declare -A distros_base=(
    [ubuntu-24.04]="ubuntu:24.04"  # TODO: Test these images
    [ubuntu-22.04]="ubuntu:22.04"  # TODO: Test these images
    [debian-12]="debian:12"  # TODO: Test these images
    [linuxmint-22]="linuxmintd/mint22.1-amd64"  # TODO: Test these images | Community image.
    [linuxmint-21]="linuxmintd/mint21.3-amd64"  # TODO: Test these images | Community image.
    [fedora-41]="fedora:41"  # TODO: Test these images
    [fedora-40]="fedora:40"  # TODO: Test these images
    [almalinux-9]="almalinux:9"  # TODO: Test these images
    [almalinux-8]="almalinux:8"  # TODO: Test these images
    [rocky-9]="rockylinux:9"  # TODO: Test these images
    [rocky-8]="rockylinux:8"  # TODO: Test these images
    [opensuse-leap-15.6]="opensuse/leap:15.6"  # Testing
    [opensuse-tumbleweed]="opensuse/tumbleweed"  # Testing
    [arch]="archlinux:latest"  # TODO: Test these images
)

# This associative array maps the distro key to its package manager.
declare -A pkg_manager=(
    [ubuntu-24.04]="apt"
    [ubuntu-22.04]="apt"
    [debian-12]="apt"
    [linuxmint-22]="apt"
    [linuxmint-21]="apt"
    [fedora-41]="dnf"
    [fedora-40]="dnf"
    [almalinux-9]="dnf"
    [almalinux-8]="dnf"
    [rocky-9]="dnf"
    [rocky-8]="dnf"
    [opensuse-leap-15.6]="zypper"
    [opensuse-tumbleweed]="zypper"
    [arch]="pacman"
)


## Build an image for each distro.
for distro in "${!distros_base[@]}"; do
    base_image="${distros_base[$distro]}"
    manager="${pkg_manager[$distro]}"
    image_tag="nadekobot-testing-${distro}"

    echo "----------------------------------------"
    echo "Building image: $image_tag"
    echo "  Base image: $base_image"
    echo "  Package manager: $manager"
    docker build --build-arg BASE_IMAGE="$base_image" \
        --build-arg PKG_MANAGER="$manager" -t "$image_tag" .
    echo "Built $image_tag"
done

echo "----------------------------------------"
echo "All images built successfully."
