#!/bin/bash
#
# This script looks at the operating system, architecture, bit type, etc., to determine
# whether or not the system is supported by NadekoBot. Once the system is deemed as
# supported, the main installer will be downloaded and executed.
#
########################################################################################
#### [ Exported and/or Globally Used Variables ]


# Refer to the 'README' note at the beginning of 'linuxAIO' for more information.
current_linuxAIO_revision=38
# Name of the main installer script.
main_installer="nadeko-main-installer"

# Similar to 'current_linuxAIO_revision', expecpt it's used as a more general tracking
# number. Instead of only being used to represent the relationship between this script
# and 'linuxAIO', it represents major changes to the installer that requires a change in
# behavior, that would otherwise result in conflict with older verisons of the script.
# TODO: Remove variable; it's not being used.
export _REVISION_NUMBER=1

## Modify output text color.
# shellcheck disable=SC2155
{
    export E_YELLOW="$(printf '\033[1;33m')"
    export E_GREEN="$(printf '\033[0;32m')"
    export E_CYAN="$(printf '\033[0;36m')"
    export E_RED="$(printf '\033[1;31m')"
    export E_NC="$(printf '\033[0m')"
    export E_GREY="$(printf '\033[0;90m')"
    export E_CLRLN="$(printf '\r\033[K')"
}


#### End of [ Exported and/or Globally Used Variables ]
########################################################################################
#### [ Functions ]


########
# Identify the operating system, version number, architecture, bit type (32 or 64), etc.
#
# Arguments:
#   None
########
detect_sys_info() {
    if [[ -f /etc/os-release ]]; then
        # shellcheck disable=SC1091
        . /etc/os-release
        E_DISTRO="$ID"
        E_VER="$VERSION_ID"  # Version: x.x.x...
        E_SVER=${E_VER//.*/}  # Version: x
        pname="$PRETTY_NAME"
    else
        E_DISTRO=$(uname -s)
        E_VER=$(uname -r)
    fi

    ## Identify bit and architecture type.
    case $(uname -m) in
        x86_64) bits="64"; E_ARCH="x64" ;;
        i*86)   bits="32"; E_ARCH="x86" ;;
        armv*)  bits="32"; E_ARCH="?" ;;
        *)      bits="?";  E_ARCH="?" ;;
    esac
}

########
# Download the latest version of 'linuxAIO' if $E_LINUXAIO_REVISION and
# $current_linuxAIO_revision aren't of equal value.
#
# Arguments:
#  None
########
linuxAIO_update() {
    echo -n "${E_YELLOW}You are using an older version of 'linuxAIO'. "
    read -rp "Press [Enter] to download the latest version.${E_NC}"
    echo "Downloading latest version of 'linuxAIO'..."

    ## Only download the newest version of 'linuxAIO', as there are some incompatible
    ## changes to 'linuxAIO' making it difficult or impossible to merge existing
    ## configurations.
    if ((E_LINUXAIO_REVISION <= 37)); then
        if [[ -f linuxAIO.sh ]]; then
            echo "Backing up 'linuxAIO.sh' as 'linuxAIO.sh.old'..."
            mv linuxAIO.sh linuxAIO.sh.old
        elif [[ -f linuxAIO ]]; then
            echo "Backing up 'linuxAIO' as 'linuxAIO.old'..."
            mv linuxAIO linuxAIO.old
        fi

        curl -O "$E_RAW_URL"/linuxAIO && sudo chmod +x linuxAIO
        echo "${E_CYAN}NOT applying existing configurations to 'linuxAIO'"
        echo "${E_GREEN}Successfully downloaded the newest version of 'linuxAIO'.${E_NC}"
    ## Download the newest version of 'linuxAIO' and apply existing changes to it.
    else
        ## Save the values of the current Configuration Variables specified in
        ## 'linuxAIO', to be set in the new 'linuxAIO'.
        local installer_branch
        local installer_branch_found
        installer_branch=$(grep '^installer_branch=.*' linuxAIO)
        installer_branch_found="$?"
        local bot_install_version
        local bot_install_version_found
        bot_install_version=$(grep '^export E_BOT_INSTALL_VERSION=.*' linuxAIO)
        bot_install_version_found="$?"

        curl -O "$E_RAW_URL"/linuxAIO && sudo chmod +x linuxAIO

        echo "Applying existing configurations to the new 'linuxAIO'..."

        # Set $installer_branch inside of the new 'linuxAIO'.
        [[ $installer_branch_found = 0 ]] \
            && sed -i "s/^installer_branch=.*/$installer_branch/" linuxAIO

        # Set $bot_install_version inside of the new 'linuxAIO'.
        [[ $bot_install_version_found = 0 ]] \
            && sed -i "s/^export E_BOT_INSTALL_VERSION=.*/$bot_install_version/" linuxAIO

        echo "${E_GREEN}Successfully downloaded the newest version of 'linuxAIO' and" \
            "applied changes to the newest version of 'linuxAIO'${E_NC}"
    fi

    clean_up "0" "Exiting" "true"
}

########
# Provide the end-user with the option to continue, even if their system isn't
# officially supported.
#
# Arguments:
#   None
########
unsupported() {
    echo "${E_RED}Your operating system is not OFFICIALLY supported for the" \
        "installation, setup, and/or use of NadekoBot" >&2
    echo "${E_YELLOW}WARNING: By continuing, you accept that unexpected behaviors" \
        "may occur. If you run into any errors or problems with the installation and" \
        "use of the NadekoBot, you are on your own.${E_NC}"
    read -rp "Would you like to continue anyways? [y/N] " choice

    choice=$(echo "$choice" | tr '[:upper:]' '[:lower:]')
    case "$choice" in
        y|yes) clear -x; execute_main_installer ;;
        *)     clean_up "0" "Exiting" ;;
    esac
}

########
# Cleanly exit the installer by removing files that aren't required unless the installer
# is currently running.
#
# Arguments:
#   $1 - required
#       Exit code.
#   $2 - required
#       Output text.
#   $3 - optional
#       True if 'Cleaning up...' should be printed with two new-line symbols.
########
clean_up() {
    # Files to be removed.
    local installer_files=("installer-prep" "file-backup" "prereqs-installer"
        "nadeko-latest-installer" "nadeko-runner" "nadeko-main-installer")

    if [[ $3 = true ]]; then echo -e "\n\nCleaning up..."
    else                     echo -e "\nCleaning up..."
    fi

    cd "$E_WORKING_DIR" || E_STDERR "Failed to move to NadekoBot's root directory" "1"
    [[ -d nadekobot_tmp ]] && rm -rf nadekobot_tmp

    for file in "${installer_files[@]}"; do
        [[ -f $file ]] && rm "$file"
    done

    echo "$2..."
    exit "$1"
}

########
# Download and execute $main_installer.
#
# Arguments:
#   None
########
execute_main_installer() {
    E_DOWNLOAD_SCRIPT "$main_installer" "true"
    ./"$main_installer"
    clean_up "$?" "Exiting"
}

########################################################################################
#### [[ Functions To Be Exported ]]


########
# Download the specified script and modify it's execution permissions.
#
# Arguments:
#   $1 - required
#       Name of the script to download.
#   $2 - optional
#       True if the script should output text indicating $1 is being downloaded.
########
E_DOWNLOAD_SCRIPT() {
    [[ $2 = true ]] && printf "Downloading '%s'..." "$1"
    curl -O -s "$E_RAW_URL"/"$1"
    sudo chmod +x "$1"
}

########
# Output an error message, and if desired, exit the script.
#
# Arguments:
#   $1 - required
#       Error message.
#   $2 - optional
#       If provided, exit with the provided value.
#   $3 - optional
#       If provided, output an additional message.
########
E_STDERR() {
    echo "${E_RED}$1${E_NC}" >&2
    [[ $3 ]] && echo -e "$3"
    [[ $2 ]] && exit "$2"
}


#### End of [[ Functions To Be Exported ]]
########################################################################################

#### End of [ Functions ]
########################################################################################
#### [ Error Traps ]


trap 'clean_up "130" "Exiting" "true"' SIGINT
trap 'clean_up "143" "Exiting" "true"' SIGTERM
trap 'clean_up "148" "Exiting" "true"' SIGTSTP


#### End of [ Error Traps ]
########################################################################################
#### [ Prepping ]


# If the current 'linuxAIO' revision number is not of equil value of the expected
# revision number...
if [[ $E_LINUXAIO_REVISION && $E_LINUXAIO_REVISION != "$current_linuxAIO_revision" ]]; then
    linuxAIO_update
    clean_up "0" "Exiting"
fi

# Change the working directory to the location of the executed script.
cd "${0%/*}" || {
    echo "${E_RED}Failed to change working directory" >&2
    echo "${E_CYAN}Change your working directory to that of the executed script${E_NC}"
    clean_up "1" "Exiting"
}

export E_WORKING_DIR="$PWD"
export E_INSTALLER_PREP="$E_WORKING_DIR/installer-prep"


#### End of [ Prepping ]
########################################################################################
#### [ Main ]


clear -x

detect_sys_info
export E_DISTRO E_SVER E_VER E_ARCH
export -f E_DOWNLOAD_SCRIPT E_STDERR

# Use $E_DISTRO if $pname is unset or null...
echo "SYSTEM INFO
Bit Type: $bits
Architecture: $E_ARCH
Distro: ${pname:=$E_DISTRO}
Distro Version: $E_VER
"

### Check if the operating system is supported by NadekoBot and the installer.
if [[ $bits = 64 ]]; then
    if [[ $E_DISTRO = "ubuntu" ]]; then
        case "$E_VER" in
            22.04|20.04|18.04) execute_main_installer ;;
            *)                 unsupported ;;
        esac
    elif [[ $E_DISTRO = "debian" ]]; then
        case "$E_SVER" in
            11|10) execute_main_installer ;;
            *)     unsupported ;;
        esac
    elif [[ $E_DISTRO = "linuxmint" ]]; then
        case "$E_SVER" in
            21|20) execute_main_installer ;;
            *)     unsupported ;;
        esac
    else
        unsupported
    fi
else
    unsupported
fi


#### End of [ Main ]
########################################################################################
