#!/bin/bash
#
# 'linuxAIO' acts as a bridge between the system running NadekoBot and 'installer-prep'.
# To avoid conflicts with installer updates, this script contains only essential code.
#
# README:
#   Since this script resides on the user's system, updates pushed to GitHub do not
#   automatically apply. To handle this, the variable $E_LINUXAIO_REVISION used to
#   tracks changes. The 'installer-prep' script has a corresponding variable,
#   $C_CURRENT_LINUXAIO_REVISION, updated alongside it. When the installer runs,
#   'installer-prep' compares these values. If they differ, the latest 'linuxAIO'
#   version is fetched from GitHub.
#
# IMPORTANT:
#   If you change $installer_branch to anything other than "main" or "dev",
#   you must install the matching version of NadekoBot. For example, if you set
#   $installer_branch to "NadekoV4", you need to install NadekoBot v4. Failing
#   to do so will likely result in a broken installation.
#
########################################################################################
####[ Variables ]#######################################################################


###
### [ Configurable Variables ]
###
### ~~~ THESE VARIABLES CAN BE MODIFIED BY THE END-USER ~~~
###
### When the installer fetches the newest 'linuxAIO', it merges all user-modified
### variables (except $installer_repo and $E_FILES_TO_BACK_UP) into the updated script.
###

# The repository containing the installer's scripts.
#
# Only modify this variable if you have created a fork and plan on customizing the
# installer.
#
# Format:  installer_repo="[github username]/[repository name]"
# Default: "StrangeRanger/NadekoBot-BashScript"
installer_repo="StrangeRanger/NadekoBot-BashScript"

# The branch of $installer_repo from which the installer downloads its scripts.
#
# Options:
#   main     = Production-ready (latest stable code)
#   dev      = Development code (may be unstable)
#   NadekoV4 = Installer version for NadekoBot v4
#
# Default: "main"
installer_branch="main"

# Files to back up when executing option 7.
#
# 1. Paths must start from Nadeko's parent directory (e.g., nadekobot/...).
# 2. Separate files with a space or list them on separate lines.
#     - Valid:   "nadekobot/creds.yml
#                 nadekobot/data/bot.yml"
#     - Valid:   "nadekobot/creds.yml nadekobot/data/bot.yml"
#     - Invalid: "nadekobot/creds.yml, nadekobot/data/bot.yml"
#     - Invalid: "nadekobot/creds.yml,nadekobot/data/bot.yml"
# 3. Neither the file name nor its path can contain spaces.
#
# Default:
#   "nadekobot/creds.yml
#    nadekobot/data/NadekoBot.db
#    nadekobot/data/bot.yml
#    nadekobot/data/gambling.yml
#    nadekobot/data/games.yml
#    nadekobot/data/images.yml
#    nadekobot/data/xp.yml
#    nadekobot/data/xp_template.json"
export E_FILES_TO_BACK_UP="nadekobot/creds.yml
nadekobot/data/NadekoBot.db
nadekobot/data/bot.yml
nadekobot/data/gambling.yml
nadekobot/data/games.yml
nadekobot/data/images.yml
nadekobot/data/xp.yml
nadekobot/data/xp_template.json"

###
### [ General Variables ]
###

# 'linuxAIO' revision number.
export E_LINUXAIO_REVISION=47
# URL to the raw code of a specified script.
export E_RAW_URL="https://raw.githubusercontent.com/$installer_repo/$installer_branch"


####[ Prepping ]########################################################################


## Change to the directory containing this script.
## NOTE:
##  We need to ensure 'linuxAIO' is in the current directory. If the user runs `bash
##  linuxAIO` instead of `./linuxAIO` while in the correct directory, ${0%/*} will
##  return 'linuxAIO' rather than '.', causing the '||' block to execute when it
##  attempts to change into a file instead of a directory.
if [[ ! -f linuxAIO ]]; then
    cd "${0%/*}" || {
        echo "Failed to change working directory" >&2
        echo "Change your working directory to that of the executed script"
        exit 1
    }
fi


####[ Main ]############################################################################


echo "Downloading the latest installer..."
curl -O "$E_RAW_URL"/installer-prep
sudo chmod +x installer-prep && ./installer-prep
exit "$?"
