#!/bin/bash
#
# 'linuxAIO' serves as an intermediary between the system running Mewdeko and
# 'installer-prep'. To prevent conflicts with installer updates, this script contains
# only the essential code.
#
# README:
#   Since this script resides on the user's system, any code changes pushed to GitHub
#   are not automatically applied to the user's version. To address this, the variable
#   $E_LINUXAIO_REVISION holds a revision number updated whenever 'linuxAIO' changes.
#   The 'installer-prep' script also contains a variable, $current_linuxAIO_revision,
#   updated alongside $E_LINUXAIO_REVISION. When the user runs the installer,
#   'installer-prep' compares these two variables. If they differ, the latest version
#   of 'linuxAIO' is fetched from GitHub.
#
########################################################################################
#### [ Variables ]


###
### [ Configurable Variables ]
###
### ~~~ THESE VARIABLES CAN BE MODIFIED BY THE END-USER ~~~
###
### Whenever the installer retrieves the newest version of 'linuxAIO', all modified
### variables, except $installer_repo and $E_FILES_TO_BACK_UP, will be applied to the
### new version of this script.
###

# The repository containing all of the scripts used by the installer.
#
# The only time that this variable should be modified, is if you have created a fork of
# the repo and plan on making your own modifications to the installer.
#
# Format:  installer_repo="[github username]/[repository name]"
# Default: "StrangeRanger/NadekoBot-BashScript"
installer_repo="StrangeRanger/NadekoBot-BashScript"

# The branch of $installer_repo that the installer will download its scripts from.
#
# Options:
#   main     = Production ready code (the latest stable code)
#   dev      = Non-production ready code (has the possibility of breaking something)
#   NadekoV3 = The version of the installer designed for NadekoBot v3
#
# Default: "main"
installer_branch="main"

# The branch/tag, of NadekoBot's official repo, that the installer will download the bot
# from.
#
# IMPORTANT:
#   Using a branch/tag containing code older than the one currently on your system,
#   increases the likelihood of failed builds due to incompatible changes in the
#   code/files copied from the current to the newly downloaded version. For this, and
#   other reasons, it's generally not recommended to to modify $E_BOT_INSTALL_VERSION.
#   This is especially true when it comes to a difference in major versions, such as v3
#   and v4.
#
# Options:
#   v4    = Latest version (the master/main branch)
#   v3    = NadekoBot v3
#   x.x.x = Any other branch/tag (refer to the NadekoBot repo for available tags and
#           branches)
#
# Default: "v4"
export E_BOT_INSTALL_VERSION="v4"

# A list of files to be backed up when executing option 7.
#
# When adding a new file to the variable below, make sure to follow these rules:
#   1. The path, starting at the project's parent directory, to the file must always be
#      included. This means that unless modified by the end-user, the beginning of the
#      path will start with 'nadekobot/', followed by the rest of the path to the file.
#   2. Each file must be separated by a single space or placed on its own line.
#       - Valid:   "nadekobot/output/creds.yml
#                   nadekobot/output/data/bot.yml"
#       - Valid:   "nadekobot/output/creds.yml nadekobot/output/data/bot.yml"
#       - Invalid: "nadekobot/output/creds.yml, nadekobot/output/data/bot.yml"
#       - Invalid: "nadekobot/output/creds.yml,nadekobot/output/data/bot.yml"
#   3. Niether the file nor the path to the file can contain a space.
#      - Valid:   'nadekobot/output/data/NadekoBot.db'
#      - Invalid: 'nadeko bot/output/data/NadekoBot.db'
#
# Default: "nadekobot/output/creds.yml
#   nadekobot/output/data/NadekoBot.db
#   nadekobot/output/data/bot.yml
#   nadekobot/output/data/gambling.yml
#   nadekobot/output/data/games.yml
#   nadekobot/output/data/images.yml
#   nadekobot/output/data/xp.yml
#   nadekobot/output/data/xp_template.json"
export E_FILES_TO_BACK_UP="nadekobot/output/creds.yml
nadekobot/output/data/NadekoBot.db
nadekobot/output/data/bot.yml
nadekobot/output/data/gambling.yml
nadekobot/output/data/games.yml
nadekobot/output/data/images.yml
nadekobot/output/data/xp.yml
nadekobot/output/data/xp_template.json"

###
### [ General Variables ]
###

# 'linuxAIO' revision number.
export E_LINUXAIO_REVISION=41
# The URL to the raw code of a specified script.
export E_RAW_URL="https://raw.githubusercontent.com/$installer_repo/$installer_branch"


####[ Main ]############################################################################


echo "Downloading the latest installer..."
curl -O "$E_RAW_URL"/installer-prep
sudo chmod +x installer-prep && ./installer-prep
exit "$?"
