#!/bin/bash
#
# Downloads and updates NadekoBot to a specified version.
#
# NOTE:
#   After each update, the user will need to manually reapply any custom strings and
#   aliases, as updates may modify or replace these files. However, the old strings and
#   aliases will be backed up as 'strings.old' and 'aliases.old.yml' respectively.
#
# Comment Key:
#   - A.1.: Prevents permission errors that can occur, particularly if the installer is
#     run once with root privileges and then again as a non-root user. This is handled
#     by ensuring '/tmp/NuGetScratch' is owned by the user running the installer.
#
########################################################################################
####[ Variables ]#######################################################################


C_NADEKOBOT_TMP=$(mktemp -d -p /tmp nadekobot-XXXXXXXXXX)
readonly C_NADEKOBOT_TMP

## File paths.
readonly C_BIN_DIR_TMP="$C_NADEKOBOT_TMP/$E_BIN_DIR"
readonly C_EXAMPLE_CREDS="$C_BIN_DIR_TMP/creds_example.yml"
readonly C_NEW_CREDS="$C_NADEKOBOT_TMP/$E_CURRENT_CREDS"
readonly C_CURRENT_DATABASE="$E_BIN_DIR/data/NadekoBot.db"
readonly C_NEW_DATABASE="$C_BIN_DIR_TMP/data/NadekoBot.db"
readonly C_CURRENT_DATA="$E_BIN_DIR/data"
readonly C_NEW_DATA="$C_BIN_DIR_TMP/data"

## GitLab project details.
readonly PROJECT_ID="9321079"
readonly API_URL="https://gitlab.com/api/v4/projects/${PROJECT_ID}"

## Non-constant variables.
service_is_active=false


####[ Functions ]#######################################################################


####
# Cleanly exits the script by removing temporary files and directories. If an error or
# premature exit is detected, it attempts to restore the original 'nadekobot' directory
# structure.
#
# PARAMETERS:
#   - $1: exit_code (Required)
#       - The initial exit code passed by the caller. Under certain conditions, it may
#         be changed to 50 to allow the calling script to continue.
#   - $2: use_extra_newline (Optional, Default: false)
#       - Whether to output an extra blank line, separating any previous output from
#         this function’s messages.
#       - Acceptable values:
#           - true
#           - false
#
# EXITS:
#   - $exit_code: Uses the provided exit code, or 50 if the conditions for continuing
#     (e.g., exit code 1 or 130) are met.
clean_exit() {
    local exit_code="$1"
    local use_extra_newline="${2:-false}"
    local exit_now=false

    trap - EXIT SIGINT
    [[ $use_extra_newline == true ]] && echo ""

    ## The exit code may be set to 50 if 'nadeko-latest-installer' should continue
    ## despite an error. Refer to 'exit_code_actions' for details.
    case "$exit_code" in
        1) exit_code=50 ;;
        0|5) ;;
        129)
            echo -e "\n${E_WARNING}Hangup signal detected (SIGHUP)"
            exit_now=true
            ;;
        130)
            echo -e "\n${E_WARNING}User interrupt detected (SIGINT)"
            exit_code=50
            ;;
        143)
            echo -e "\n${E_WARNING}Termination signal detected (SIGTERM)"
            exit_now=true
            ;;
        *)
            echo -e "\n${E_WARNING}Exiting with exit code: $exit_code"
            exit_now=true
            ;;
    esac

    echo "${E_INFO}Cleaning up..."
    [[ -d "$C_NADEKOBOT_TMP" ]] && rm -rf "$C_NADEKOBOT_TMP" &>/dev/null

    (
        if [[ -d nadekobot && ! -d nadekobot.old && -d nadekobot.old.old ]]; then
            echo "${E_WARNING}Unable to complete installation"
            echo "${E_INFO}Attempting to restore original version of 'nadekobot'..."
            mv nadekobot.old.old nadekobot.old || exit 1
        elif [[ ! -d nadekobot && -d nadekobot.old ]]; then
            echo "${E_WARNING}Unable to complete installation"
            echo "${E_INFO}Attempting to restore original version of 'nadekobot'..."
            mv nadekobot.old nadekobot || exit 1

            if [[ -d nadekobot.old.old ]]; then
                mv nadekobot.old.old nadekobot.old \
                    || E_STDERR \
                        "Failed to rename 'nadekobot.old.old' as 'nadekobot.old'" \
                        "" "${E_NOTE}Please rename it manually"
            fi
        elif [[ -d nadekobot && -d nadekobot.old && -d nadekobot.old.old ]]; then
            rm -rf nadekobot.old.old \
                || E_STDERR "Failed to remove 'nadekobot.old.old'" "" \
                    "${E_NOTE}Please remove 'nadekobot.old.old' manually"
        fi
    ) || E_STDERR "Failed to restore 'nadekobot'" "$?" \
        "${E_NOTE}We will exit completely to prevent data loss"

    if [[ $exit_now == false ]]; then
        read -rp "${E_NOTE}Press [Enter] to return to the main menu"
    fi

    exit "$exit_code"
}

####
# Retrieves all available NadekoBot versions from the GitLab API and prompts the user to
# choose one for installation.
#
# NEW GLOBALS:
#   - C_BOT_VERSION: The selected version of NadekoBot to install.
#   - C_ARCHIVE_NAME: The archive filename to download.
#   - C_ARCHIVE_URL: The direct URL from which the archive is downloaded.
#
# EXITS:
#   - 1: If fetching releases from the GitLab API fails or if no releases are found.
fetch_versions() {
    local response; response=$(curl -sS -w "%{http_code}" "${API_URL}/releases")
    local http_code="${response: -3}"
    local response_body="${response:0:${#response}-3}"
    local versions

    if (( http_code != 200 )); then
        E_STDERR "Failed to fetch releases from '${API_URL}'" "1"
    fi

    # TODO: Confirm that the '||' operator works as intended here.
    mapfile -t versions < <(echo "$response_body" | jq -r '.[].tag_name' | sort -V -r) \
        || E_STDERR "Failed to parse releases" "1"

    if (( ${#versions[@]} == 0 )); then
        E_STDERR "No releases found" "1"
    fi

    echo "${E_NOTE}Select version to install:"
    select version in "${versions[@]}"; do
        if [[ -n $version ]]; then
            C_BOT_VERSION="$version"
            C_ARCHIVE_NAME="nadekobot-v${version}.tar"
            C_ARCHIVE_URL="$API_URL/packages/generic/NadekoBot-build/$C_BOT_VERSION/${C_BOT_VERSION}-linux-${E_ARCH}-build.tar"
            break
        else
            echo "${E_ERROR}Invalid selection"
        fi
    done
}


####[ Trapping Logic ]##################################################################


trap 'clean_exit "129" "true"' SIGHUP
trap 'clean_exit "130" "true"' SIGINT
trap 'clean_exit "143" "true"' SIGTERM
trap 'clean_exit "$?" "true"'  EXIT


####[ Main ]############################################################################


read -rp "${E_NOTE}We will now set up NadekoBot. Press [Enter] to begin."
cd "$C_NADEKOBOT_TMP" \
    || E_STDERR "Failed to change working directory to '$C_NADEKOBOT_TMP'" "1"

if [[ $E_SERVICE_STATUS == "active" ]]; then
    service_is_active=true
    E_STOP_SERVICE
fi

fetch_versions

###
### [ Download NadekoBot Archive ]
###

echo "${E_INFO}Downloading '${C_BOT_VERSION}' for '${E_ARCH}'..."
curl -L -o "$C_ARCHIVE_NAME" "$C_ARCHIVE_URL" \
    || E_STDERR "Failed to download '${C_BOT_VERSION}'" "1"

echo "${E_INFO}Extracting '${C_ARCHIVE_NAME}'..."
tar -xf "$C_ARCHIVE_NAME" || E_STDERR "Failed to extract '${C_ARCHIVE_NAME}'" "1"

archive_dir_name=$(tar -tf "$C_ARCHIVE_NAME" | head -1 | cut -f1 -d "/")
mv "$archive_dir_name" "$E_BIN_DIR"
unset archive_dir_name
chmod +x "${E_BIN_DIR}/${E_BOT_EXECUTABLE}"
cd "$E_ROOT_DIR" || E_STDERR "Failed to change working directory to '$E_ROOT_DIR'" "1"


###
### [ Move Credentials, Database, and Other Data ]
###
### Moves the credentials, database, and other NadekoBot data to the new version
### directory. In case 'nadekobot' already exists, it is renamed to 'nadekobot.old'
### (with a further fallback of 'nadekobot.old.old'), making it easier to revert to a
### previous version if needed.
###

(
    if [[ ! -f $E_CURRENT_CREDS ]]; then
        echo "${E_INFO}Copying '${C_EXAMPLE_CREDS##*/}' as '${C_NEW_CREDS##*/}'" \
            "to '${C_NEW_CREDS%/*}'..."
        cp -f "$C_EXAMPLE_CREDS" "$C_NEW_CREDS" || exit 1
    else
        echo "${E_INFO}Copying '${C_NEW_CREDS##*/}' to '${C_NEW_CREDS%/*}'..."
        cp -f "$E_CURRENT_CREDS" "$C_NEW_CREDS" || exit 1
    fi
) || E_STDERR "Failed to copy credentials" "1"


if [[ -d nadekobot ]]; then
    if [[ ! -f $C_CURRENT_DATABASE ]]; then
        echo "${E_WARNING}'$C_CURRENT_DATABASE' could not be found"
        echo "${E_NOTE}Skipping copying the database..."
    else
        echo "${E_INFO}Copying '${C_CURRENT_DATABASE} to the '${C_NEW_DATABASE%/*}'..."
        cp -rT "$C_CURRENT_DATABASE" "$C_NEW_DATABASE" \
            || E_STDERR "Failed to copy database" "1"
    fi

    echo "${E_INFO}Copying other data to the new version..."
    (
        ## Temporarily rename the new version's strings and aliases so they won't be
        ## overwritten.
        mv -fT "$C_NEW_DATA"/strings "$C_NEW_DATA"/strings.new || exit 1
        mv -f "$C_NEW_DATA"/aliases.yml "$C_NEW_DATA"/aliases.new.yml || exit 1

        # Copy current data directory into the new one, overwriting matching
        # files/folders.
        cp -rT "$C_CURRENT_DATA" "$C_NEW_DATA" || exit 1

        # Remove any old backups of strings and aliases.
        rm -rf "$C_NEW_DATA"/strings.old "$C_NEW_DATA"/aliases.old.yml 2>/dev/null

        ## Back up the overwritten strings and aliases before restoring the new ones.
        mv -fT "$C_NEW_DATA"/strings "$C_NEW_DATA"/strings.old || exit 1
        mv -f "$C_NEW_DATA"/aliases.yml "$C_NEW_DATA"/aliases.old.yml || exit 1

        ## Restore the new version's strings and aliases.
        mv -fT "$C_NEW_DATA"/strings.new "$C_NEW_DATA"/strings || exit 1
        mv -f "$C_NEW_DATA"/aliases.new.yml "$C_NEW_DATA"/aliases.yml || exit 1
    ) || E_STDERR "An error occurred while copying other data" "$?"

    echo "${E_INFO}Replacing 'nadekobot' with '${C_NADEKOBOT_TMP}/nadekobot'..."
    (
        if [[ -d nadekobot.old ]]; then
            mv nadekobot.old nadekobot.old.old || exit 5
        fi

        mv nadekobot nadekobot.old || exit 5
        mv "$C_NADEKOBOT_TMP"/nadekobot nadekobot || exit 5

        if [[ -d nadekobot.old.old ]]; then
            rm -rf nadekobot.old.old \
                || E_STDERR "Failed to remove 'nadekobot.old.old'" "" \
                    "${E_NOTE}Please remove 'nadekobot.old.old' manually"
        fi
    ) || E_STDERR "An error occurred while replacing 'nadekobot'" "$?"
else
    echo "${E_INFO}Moving '$C_NADEKOBOT_TMP/nadekobot' to 'nadekobot'..."
    mv "$C_NADEKOBOT_TMP"/nadekobot "$E_ROOT_DIR" \
        || E_STDERR "Failed to move '${C_NADEKOBOT_TMP}' to 'nadekobot'" "1"
    rmdir "$C_NADEKOBOT_TMP" &>/dev/null
fi

###
### [ Clean Up and Present Results ]
###

echo ""
echo "${E_SUCCESS}Finished setting up NadekoBot"

if [[ $service_is_active == true ]]; then
    echo "${E_NOTE}'$E_SERVICE_NAME' was stopped to update NadekoBot and needs to be" \
        "started using one of the run modes in the installer menu"
fi

clean_exit 0
