#!/bin/bash
#
# This script downloads and updates NadekoBot to the latest version.
#
# Comment Key:
#   - A.1.: To prevent permission errors that can occur, especially when the installer
#       is run with root privileges and later as a non-root user, it's necessary to
#       ensure that '/tmp/NuGetScratch' and '/home/$USER/.nuget' are owned by the user
#       currently running the installer.
#
########################################################################################
####[ Variables ]#######################################################################


export DOTNET_CLI_TELEMETRY_OPTOUT=1  # Used when compiling code.

C_NADEKOBOT_TMP=$(mktemp -d -p /tmp nadekobot.XXXXXXXXXX)
readonly C_NADEKOBOT_TMP

readonly C_NADEKOBOT_URL="https://gitlab.com/Kwoth/nadekobot"
readonly C_EXAMPLE_CREDS="nadekobot/src/NadekoBot/creds_example.yml"
readonly C_CURRENT_CREDS="nadekobot/output/creds.yml"
readonly C_NEW_CREDS="$C_NADEKOBOT_TMP/nadekobot/output/creds.yml"
readonly C_CURRENT_DATABASE="nadekobot/output/data/NadekoBot.db"
readonly C_NEW_DATABASE="$C_NADEKOBOT_TMP/nadekobot/output/data/NadekoBot.db"
readonly C_CURRENT_DATA="nadekobot/output/data"
readonly C_NEW_DATA="$C_NADEKOBOT_TMP/nadekobot/output/data"

service_is_active=false


####[ Trapping Logic ]##################################################################


trap 'clean_exit "130" "true"' SIGINT
trap 'clean_exit "143" "true"' SIGTERM
trap 'clean_exit "129" "true"' SIGHUP
trap 'clean_exit "131" "true"' SIGQUIT
trap 'clean_exit "$?" "true"'  EXIT


####[ Main ]############################################################################


read -rp "${E_NOTE}We will now download/update NadekoBot. Press [Enter] to begin."

###
### [ Stop Service ]
###

if [[ $E_SERVICE_STATUS == "active" ]]; then
    service_is_active=true
    E_STOP_SERVICE
fi

###
### [ Create Backup and Update ]
###

cd "$C_NADEKOBOT_TMP" || E_STDERR "Failed to change working directory" "1"

echo "${E_INFO}Downloading NadekoBot into '$C_NADEKOBOT_TMP'..."
git clone -b "$E_BOT_INSTALL_VERSION" --recursive --depth 1 "$C_NADEKOBOT_URL" \
    || E_STDERR "Failed to download NadekoBot" "1"

## A.1.
if [[ -d /tmp/NuGetScratch ]]; then
    echo "${E_INFO}Modifying ownership of '/tmp/NuGetScratch'..."
    sudo chown -R "$USER":"$USER" /tmp/NuGetScratch \
        || E_STDERR "Failed to to modify the ownership of '/tmp/NuGetScratch'" "1"
fi

## A.1.
## Commented out because I don't believe it's necessary. But I'm leaving it here for
## for now until I'm 100% sure it's not needed.
#if [[ -d  /home/$USER/.nuget ]]; then
#    echo "${E_INFO}Modifying ownership of '/home/$USER/.nuget'..."
#    sudo chown -R "$USER":"$USER" /home/"$USER"/.nuget \
#        || E_STDERR "Failed to to modify the ownership of '/home/$USER/.nuget'..." "1"
#fi

echo "${E_INFO}Building NadekoBot..."
cd nadekobot || E_STDERR "Failed to change directory to 'nadekobot'" "1"
dotnet restore -f --no-cache || E_STDERR "Failed to restore .NET packages" "1"
dotnet build src/NadekoBot/NadekoBot.csproj -c Release -o output/ \
    || E_STDERR "Failed to build NadekoBot" "1"
cd "$E_WORKING_DIR" || E_STDERR "Failed to change directory to '$E_WORKING_DIR'" "1"

###
### [ Move Credentials, Database, and Other Data ]
###
### Move credentials, database, and other data to the new version of NadekoBot.
###

if [[ ! -f $C_CURRENT_CREDS ]]; then
    echo "${E_WARNING}'$C_CURRENT_CREDS' could not be found"
    echo "${E_INFO}Copying '${C_EXAMPLE_CREDS##*/}' as '${C_NEW_CREDS##*/}'" \
        "to '${C_NEW_CREDS%/*}'..."
    cp -f "$C_EXAMPLE_CREDS" "$C_CURRENT_CREDS"
else
    echo "${E_INFO}Copying '${C_NEW_CREDS##*/}' to '${C_NEW_CREDS%/*}'..."
    cp -f "$C_CURRENT_CREDS" "$C_NEW_CREDS"
fi


# If the old and new versions of NadekoBot exist, move the database and other data.
if [[ -d $C_NADEKOBOT_TMP/nadekobot && -d nadekobot ]]; then
    if [[ ! -f $C_CURRENT_DATABASE ]]; then
        echo "${E_WARNING}'$C_CURRENT_DATABASE' could not be found"
    else
        echo "${E_INFO}Copying '${C_CURRENT_DATABASE} to the '${C_NEW_DATABASE%/*}'..."
        cp -RT "$C_CURRENT_DATABASE" "$C_NEW_DATABASE"
    fi

    echo "${E_INFO}Copying other data to the new version..."

    ### IMPORTANT:
    ###     The end-user will have to manually re-add their strings after each update as
    ###     updates may cause a number of strings to become obsolete, changed, etc.
    ###     However, old user's strings will be backed up as strings_old.

    ## Back up new strings to reverse rewrite.
    rm -rf "$C_NEW_DATA"/strings_new &>/dev/null
    mv -fT "$C_NEW_DATA"/strings "$C_NEW_DATA"/strings_new

    ## Delete old string backups.
    rm -rf "$C_CURRENT_DATA"/strings_old &>/dev/null
    rm -rf "$C_CURRENT_DATA"/strings_new &>/dev/null

    # Back up new aliases to reverse rewrite.
    mv -f "$C_NEW_DATA"/aliases.yml "$C_NEW_DATA"/aliases_new.yml

    # Move old data folder contents (and overwrite).
    cp -RT "$C_CURRENT_DATA" "$C_NEW_DATA"

    # Back up old aliases.
    mv -f "$C_NEW_DATA"/aliases.yml "$C_NEW_DATA"/aliases_old.yml
    # Restore new aliases.
    mv -f "$C_NEW_DATA"/aliases_new.yml "$C_NEW_DATA"/aliases.yml

    # Back up old strings.
    mv -f "$C_NEW_DATA"/strings "$C_NEW_DATA"/strings_old
    # Restore new strings.
    mv -f "$C_NEW_DATA"/strings_new "$C_NEW_DATA"/strings

    rm -rf nadekobot.old && mv -f nadekobot nadekobot.old
fi

mv "$C_NADEKOBOT_TMP"/nadekobot . && rmdir "$C_NADEKOBOT_TMP"

###
### [ Clean Up and Present Results ]
###

echo -e "\n${E_SUCCESS}Finished downloading/updating NadekoBot${E_NC}"

if [[ $service_is_active == true ]]; then
    echo "${E_NOTE}'$E_SERVICE_NAME' was stopped to update NadekoBot and needs to be" \
        "started using one of the run modes in the installer menu${E_NC}"
fi

read -rp "${E_NOTE}Press [Enter] to apply any existing changes to the installers"
