#!/bin/bash
#
#
#
########################################################################################
####[ Functions ]#######################################################################


####
# Revert the changes made to 'linuxAIO' if the script is interrupted.
#
# EXITS:
#   - 1: The entire script is to be exited.
revert() {
    if [[ -f linuxAIO.old && ! -f linuxAIO ]]; then
        echo ""
        echo -n "${E_INFO}Restoring the previous version of 'linuxAIO'..."
        mv linuxAIO.old linuxAIO
        chmod +x linuxAIO
    fi

    exit 1
}

####
# Download the latest version of 'linuxAIO' and transfer existing configurations to it.
download_and_transfer() {
    local installer_branch
    local installer_branch_found
    installer_branch=$(grep '^installer_branch=.*' linuxAIO.old)
    installer_branch_found="$?"

    echo "${E_INFO}Downloading latest version of 'linuxAIO'..."

    curl -O "$E_RAW_URL"/linuxAIO || {
        E_STDERR "Failed to download 'linuxAIO'"
        revert
    }
    chmod +x linuxAIO

    echo "${E_INFO}Applying existing configurations to the new 'linuxAIO'..."

    [[ $installer_branch_found == 0 ]] \
        && sed -i "s/^installer_branch=.*/$installer_branch/" linuxAIO
}

####
# Perform additional checks and modifications for 'linuxAIO' revision 45 and before.
#
# RETURNS:
#   0: The function has completed or there is nothing to do.
revision_45() {
    [[ -f nadekobot/creds_example.yml && -f nadekobot/NadekoBot.dll ]] \
        && return 0

    echo "${E_WARNING}The new version of 'linuxAIO' has several breaking changes from" \
        "revision 45 and earlier. They will be handled automatically."
    echo "${E_NOTE}For more information, view the 'v5.0.0' release notes at" \
            "https://github.com/StrangeRanger/NadekoBot-BashScript/blob/main/CHANGELOG.md"
    read -rp "${E_NOTE}Press [Enter] to continue"

    echo "${E_INFO}Renaming 'nadekobot' to 'nadekobot.rev45.bak'..."
    mv nadekobot nadekobot.rev45.bak

    echo "${E_INFO}Copying 'nadekobot.rev45.bak/output' to 'nadekobot'..."
    cp -r nadekobot.rev45.bak/output nadekobot

    echo "${E_IMPORTANT}It is highly recommended to downloaded the newest version of" \
        "NadekoBot before continuing."
}


####[ Trapping Logic ]##################################################################


trap 'revert' SIGINT


####[ Main ]############################################################################


printf "%s" "$E_CLRLN"  # Clear the "Downloading 'linuxAIO'..." message.
read -rp "${E_NOTE}Press [Enter] to download the latest version"

if [[ -f linuxAIO.old ]]; then
    echo "${E_INFO}Removing existing 'linuxAIO.old'..."
    rm linuxAIO.old
fi

if [[ -f linuxAIO.sh ]]; then
    echo "${E_INFO}Backing up 'linuxAIO.sh' as 'linuxAIO.old'..."
    mv linuxAIO.sh linuxAIO.old
elif [[ -f linuxAIO ]]; then
    echo "${E_INFO}Backing up 'linuxAIO' as 'linuxAIO.old'..."
    mv linuxAIO linuxAIO.old
fi

chmod -x linuxAIO.old

## Due to changes in 'linuxAIO', the existing configurations cannot be directly
## applied to the newest version of 'linuxAIO'. As a result, the existing
## configurations will instead be backed up as 'linuxAIO.old', and the end-user will
## have to reconfigure 'linuxAIO' manually.
##
# shellcheck disable=SC2153
#   $_LINUXAIO_REVISION and $_RAW_URL are from revision 38 and earlier. This means
#   that the if statement doesn't need to test for $E_LINUXAIO_REVISION to check if
#   the current version of 'linuxAIO' is revision 38 or earlier.
if [[ $_LINUXAIO_REVISION ]] && ((_LINUXAIO_REVISION <= 38)); then
    curl -O "$_RAW_URL/linuxAIO" || {
        E_STDERR "Failed to download 'linuxAIO'"
        revert
    }
    chmod +x linuxAIO

    echo "${E_NOTE}Existing configurations will NOT be applied to 'linuxAIO'"
    echo "${E_SUCCESS}Successfully downloaded the newest version of 'linuxAIO'"
## Perform additional checks and modifications for specific revisions, then transfer
## configurations.
elif (( E_LINUXAIO_REVISION != E_CURRENT_LINUXAIO_REVISION )); then
    echo "${E_INFO}Performing additional revision checks..."

    if (( E_LINUXAIO_REVISION <= 45 )); then
        revision_45
    fi

    download_and_transfer

    echo "${E_SUCCESS}Successfully downloaded the newest version of 'linuxAIO' with" \
        "existing configurations applied"
    echo "${E_IMPORTANT}Review the 'linuxAIO.old' file for configurations that were not" \
        "automatically transferred to the new 'linuxAIO'"
else
    echo "${E_SUCCESS}You are already using the latest version of 'linuxAIO'"
fi
